/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO_interface.h"
#include "RCC_interface.h"
#include "USART_interface.h"
#include "BL.h"

extern USART_ConfigReg_t USART2 ;

int main(void)
{
	RCC_Set_CLK_Status(HSI, ON);
	RCC_Set_SysClk(HSI_SYS);
	RCC_APB1Enable(APB1_USART2);
	RCC_AHB1EnableClk(AHB1_GPIOA);
	RCC_AHB1EnableClk(AHB1_GPIOC);
	RCC_AHB1EnableClk(AHB1_CRC);
	RCC_voidAHB1EnablePerapheralClock_LowPower(AHB1_FLITF);


	USART_Init(&USART2);
	/*********************	GPIO Pins configurations ***********************/
		PinConfig_t USARTPinRX =
		{
				.AltFunc = AF7,
				.Mode = ALTERNATIVE_FUNCTION,
				.PinNum = PIN2,
				.Port = PORTA,
				.PullType = PUSH_PULL,
				.Speed = LOW
		};

		PinConfig_t USARTPinTX =
		{
				.AltFunc = AF7,
				.Mode = ALTERNATIVE_FUNCTION,
				.PinNum = PIN3,
				.Port = PORTA,
				.PullType = PUSH_PULL,
				.Speed = LOW
		};
		PinConfig_t Button =
		{
				.Mode = INPUT,
				.PinNum = PIN13,
				.Port = PORTC,
				.PullType = NOPULL
	 	};

		GPIO_u8PinInit(&USARTPinRX);
		GPIO_u8PinInit(&USARTPinTX);
		GPIO_u8PinInit(&Button);

		uint8_t Local_u8ButtonStatus;

		GPIO_u8ReadPinValue(Button.Port,Button.PinNum, &Local_u8ButtonStatus);

		if(Local_u8ButtonStatus == PIN_LOW)
		{
			/*Jump to user application */
			BL_voidJumpToUserApp();
		}
		else
		{
			/* receive packets from the host*/
			BL_voidReceivePckt();
		}

    /* Loop forever */
	for(;;);
}
